import {WPWebPage} from '@models/swagger/App/Domain/Integrations/WordPress/Seo/Entities/WebPages/WPWebPage';
import {WPVariables} from '@models/swagger/App/Domain/Integrations/WordPress/Common/Entities/WPVariables';
import {WPWebsite} from '@models/swagger/App/Domain/Integrations/WordPress/Seo/Entities/Websites/WPWebsite';
import {WPAccount} from '@models/swagger/App/Domain/Integrations/WordPress/Common/Entities/Accounts/WPAccount';

  export const WPWebPageSocialDescriptionMetaTagObjectType = {
    App_Domain_Integrations_WordPress_Seo_Entities_WebPages_Content_Elements_MetaTags_Social_WPWebPageSocialDescriptionMetaTag : "App\\Domain\\Integrations\\WordPress\\Seo\\Entities\\WebPages\\Content\\Elements\\MetaTags\\Social\\WPWebPageSocialDescriptionMetaTag",
  }

export type WPWebPageSocialDescriptionMetaTag = {
   /**
    * The type of the meta-tag
    */
  type?: string
   /**
    * The parsed content
    */
  parsed?: string
   /**
    * The ID of the meta-tag
    */
  id?: number
   /**
    * The ID of the post that the meta-tag is for
    */
  postId?: number
  post?: WPWebPage
   /**
    * The content of the meta-tag
    */
  content?: string
   /**
    * The template of the meta-tag
    */
  template?: string
   /**
    * Whether the meta-tag should be auto-generated
    */
  autoGenerated?: boolean
  variables?: WPVariables
   /**
    * The unique key of the meta-tag
    */
  uniqueKey?: string
  site?: WPWebsite
   /**
    * The ID of the WordPress user that the meta-tag is for
    */
  userId?: number
  user?: WPAccount
   /**
    * The fully qualified class name of the object
    */
  objectType: typeof WPWebPageSocialDescriptionMetaTagObjectType[keyof typeof WPWebPageSocialDescriptionMetaTagObjectType] 
}
  
  