import {WPWebPage} from '@models/swagger/BeyondSEO/Domain/Integrations/WordPress/Seo/Entities/WebPages/WPWebPage';
import {WPVariables} from '@models/swagger/BeyondSEO/Domain/Integrations/WordPress/Common/Entities/WPVariables';
import {WPWebsite} from '@models/swagger/BeyondSEO/Domain/Integrations/WordPress/Seo/Entities/Websites/WPWebsite';
import {WPAccount} from '@models/swagger/BeyondSEO/Domain/Integrations/WordPress/Common/Entities/Accounts/WPAccount';

  export const WPWebPageKeywordsMetaTagObjectType = {
    BeyondSEO_Domain_Integrations_WordPress_Seo_Entities_WebPages_Content_Elements_MetaTags_Tags_WPWebPageKeywordsMetaTag : "BeyondSEO\\Domain\\Integrations\\WordPress\\Seo\\Entities\\WebPages\\Content\\Elements\\MetaTags\\Tags\\WPWebPageKeywordsMetaTag",
  }

export type WPWebPageKeywordsMetaTag = {
   /**
    * The type of the meta tag
    */
  type?: string
   /**
    * $primaryKeyword The primary keyword
    */
  primaryKeyword?: string
   /**
    * $additionalKeywords Additional keywords
    */
  additionalKeywords?: string []
   /**
    * The ID of the meta-tag
    */
  id?: number
   /**
    * The ID of the post that the meta-tag is for
    */
  postId?: number
  post?: WPWebPage
   /**
    * The content of the meta-tag
    */
  content?: string
   /**
    * The template of the meta-tag
    */
  template?: string
   /**
    * Whether the meta-tag should be auto-generated
    */
  autoGenerated?: boolean
  variables?: WPVariables
   /**
    * The unique key of the meta-tag
    */
  uniqueKey?: string
  site?: WPWebsite
   /**
    * The ID of the WordPress user that the meta-tag is for
    */
  userId?: number
  user?: WPAccount
   /**
    * The fully qualified class name of the object
    */
  objectType: typeof WPWebPageKeywordsMetaTagObjectType[keyof typeof WPWebPageKeywordsMetaTagObjectType] 
}
  
  